spring.application.name=eureka-server
server.port=8761
eureka.client.register-with-eureka=false

management.endpoints.web.exposure.include=*
management.endpoint.prometheus.enabled=true
management.metrics.export.prometheus.enabled=true

logging.file.name=logs/eureka-service.log
logging.level.root=INFO